from typing import List, Tuple, Dict, Any
# We import LLMClient for type hinting in our synthesize method.
from query.llm_client import LLMClient

# RAG SYNTHESIS means combining the retrieval phase (fetching relevant text facts from a database)
# with the generation phase (an LLM writing a natural response). Instead of asking the LLM 
# to answer from its general memory, we feed it specific facts and instruct it to synthesize 
# a coherent response based ONLY on those facts.
#
# CONFIDENCE SCORE matters because it tells the user how reliable the generated response is. 
# If the retriever fetches documents with low similarity scores, it indicates the database lacks
# matching context, so the LLM's response is highly likely to be a guess or a refusal.
#
# PROMPT STRUCTURE:
# 1. System Role: Establishes the agent's persona ("DocMind").
# 2. Context Chunks: Standardized list of retrieved text segments with reference headers ([Chunk 1], etc.).
# 3. Grounding Instructions: Strict rules commanding the LLM to only use the context and cite sources.
# 4. User Query: The user's active question.

class ResponseSynthesizer:
    """
    Synthesizer that constructs prompts, invokes the LLM, and formats RAG responses with confidence scores.
    """
    def __init__(self):
        pass

    def synthesize(
        self, 
        user_question: str, 
        retrieved_chunks: List[Tuple[str, float]], 
        llm_client: LLMClient
    ) -> Dict[str, Any]:
        """
        Synthesizes a response to the user's question grounded in the retrieved document chunks.
        
        Parameters:
            user_question (str): The question asked by the user.
            retrieved_chunks (List[Tuple[str, float]]): Chunks fetched from Qdrant as (text, similarity_score) tuples.
            llm_client (LLMClient): The active LLM client used to generate responses.
            
        Returns:
            Dict[str, Any]: A dictionary containing:
                - 'answer' (str): The response generated by the LLM.
                - 'confidence_score' (float): Average similarity score scaled between 0 and 1.
                - 'sources' (List[str]): List of raw chunk texts used as background context.
        """
        # If no chunks are retrieved, return a helpful default message without calling the LLM
        if not retrieved_chunks:
            return {
                "answer": "I'm sorry, but I couldn't find any relevant documents to answer your question.",
                "confidence_score": 0.0,
                "sources": []
            }

        # (1) Construct the context block with clear chunk numbering
        context_blocks = []
        for index, (text, score) in enumerate(retrieved_chunks):
            context_blocks.append(f"--- Chunk {index + 1} (Relevance Score: {score:.4f}) ---\n{text}")
        context_str = "\n\n".join(context_blocks)

        # (2) Formulate the RAG prompt instructing the LLM to write answers and cite sources
        prompt = f"""You are DocMind, an intelligent document assistant.
Answer the User Question using only the retrieved document chunks provided below. 

Rules:
1. Always cite which chunk(s) (e.g. [Chunk 1], [Chunk 2]) you used in your response.
2. Be factual, concise, and professional.
3. If the answer cannot be derived from the document chunks, state that you do not have sufficient information.

Retrieved Document Chunks:
{context_str}

User Question: {user_question}

Answer:"""

        # (3) Query the LLM using our unified LLMClient
        answer = llm_client.generate(prompt)

        # (4) Calculate the confidence score as the average of the similarity scores
        # We clamp the score between 0.0 and 1.0 just in case.
        scores = [score for _, score in retrieved_chunks]
        avg_score = sum(scores) / len(scores)
        confidence_score = max(0.0, min(1.0, float(avg_score)))

        # Extract only the raw text values for the list of sources returned
        sources_list = [text for text, _ in retrieved_chunks]

        # (5) Compile and return response dictionary
        return {
            "answer": answer,
            "confidence_score": round(confidence_score, 4),
            "sources": sources_list
        }
