import datetime
from sqlalchemy import Column, String, Integer, Float, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship, declarative_base

# The declarative_base() function creates a base class from which all mapped database models inherit.
# Inheriting from this class automatically registers our models with SQLAlchemy's internal metadata.
Base = declarative_base()

# DATABASE NORMALIZATION:
# We separate Conversations and Messages into two distinct, normalized tables:
# 1. A Conversation represents a single chat session.
# 2. A Message represents an individual text message (either user query or LLM response) within a session.
#
# By splitting them, we adhere to relational database best practices (1-to-many relationship):
# - It avoids duplicating conversation metadata (like start time or session ID) for every single message.
# - It allows us to query messages independently, sort them by timestamp, and dynamically append them.
# - A Conversation can contain zero, one, or many Messages.

def get_utc_now_naive():
    """
    Helper to return a naive UTC datetime, avoiding python 3.12 deprecation warnings.
    """
    return datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)

class Conversation(Base):
    """
    Represents a single chat session between a user and the RAG model.
    """
    __tablename__ = "conversations"

    # UUID unique identifier generated by the application
    id = Column(String, primary_key=True, index=True)
    
    # DateTime stamp of when the session was created
    created_at = Column(DateTime, default=get_utc_now_naive)

    # Establish a one-to-many relationship with the Message table.
    # cascade="all, delete-orphan" ensures that if a Conversation is deleted, 
    # all its associated messages are automatically deleted from the database.
    # back_populates links this relationship back to the 'conversation' property in the Message class.
    messages = relationship("Message", back_populates="conversation", cascade="all, delete-orphan", order_by="Message.timestamp")


class Message(Base):
    """
    Represents a single message exchange (either user question or model answer) in a conversation.
    """
    __tablename__ = "messages"

    # Primary key that automatically increments with each message inserted
    id = Column(Integer, primary_key=True, autoincrement=True, index=True)

    # FOREIGN KEY:
    # A foreign key is a column (or set of columns) that establishes a link between data in two tables.
    # Here, 'conversation_id' references the primary key 'id' of the 'conversations' table.
    # This prevents orphaned messages (we cannot insert a message for a conversation ID that does not exist)
    # and enforces database referential integrity.
    conversation_id = Column(String, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False)

    # The role of the sender: 'user' or 'assistant'
    role = Column(String, nullable=False)

    # The text content of the message
    content = Column(Text, nullable=False)

    # Confidence score (average similarity score of the sources used to answer)
    # Only applicable for role='assistant', hence nullable=True
    confidence_score = Column(Float, nullable=True)

    # Timestamp of when this specific message was created/sent
    timestamp = Column(DateTime, default=get_utc_now_naive)

    # Establish the relationship back to the parent Conversation class
    conversation = relationship("Conversation", back_populates="messages")
